repos:

- repo: local
  hooks:
    - id: testing
      name: Run Testing Suite.
      entry: main.bash
      language: unsupported_script
      fail_fast: true
      stages: [pre-commit]

- repo: local
  hooks:
    - id: version
      name: Increment Container Version.
      entry: python .hooks/main.py
      fail_fast: true
      language: python
      files: ^bats/tests/
      additional_dependencies:
        - jinja2
        - semver
      stages: [manual]
