
- repo: local
    hooks:
      - id: write-version
        name: Increment Container Version.
        entry: python .python/hooks/write_version.py
        fail_fast: true
        language: python
        additional_dependencies:
          - jinja2
        stages: [pre-commit]
