repos:

- repo: local
  hooks:
    - id: testing
      name: Run Testing Suite.
      entry: main.bash
      language: unsupported_script
      fail_fast: true
      stages: [pre-commit, manual]
      pass_filenames: false

- repo: local
  hooks:
    - id: increment-version-by-patch
      name: Increment Container Version.
      entry: python .hooks/main.py --patch
      fail_fast: true
      language: python
      additional_dependencies:
        - semver
      stages: [manual]
      args: [--project-root, "."]
      pass_filenames: false

- repo: local
  hooks:
    - id: increment-version-by-minor
      name: Increment Container Version.
      entry: python .hooks/main.py --minor
      fail_fast: true
      language: python
      additional_dependencies:
        - semver
      stages: [manual]
      args: [--project-root, "."]
      pass_filenames: false

- repo: local
  hooks:
    - id: increment-version-by-minor
      name: Increment Container Version.
      entry: python .hooks/main.py --minor
      fail_fast: true
      language: python
      additional_dependencies:
        - semver
      stages: [manual]
      args: [--project-root, "."]
      pass_filenames: false

- repo: local
  hooks:
    - id: increment-version-by-minor
      name: Increment Container Version.
      entry: python .hooks/main.py --major
      fail_fast: true
      language: python
      additional_dependencies:
        - semver
      stages: [manual]
      args: [--project-root, "."]
      pass_filenames: false

- repo: local
  hooks:
    - id: increment-version-by-minor
      name: Increment Container Version.
      entry: python .hooks/main.py --pre
      fail_fast: true
      language: python
      additional_dependencies:
        - semver
      stages: [manual]
      args: [--project-root, "."]
      pass_filenames: false

- repo: local
  hooks:
    - id: increment-version-by-minor
      name: Increment Container Version.
      entry: python .hooks/main.py --build
      fail_fast: true
      language: python
      additional_dependencies:
        - semver
      stages: [manual]
      args: [--project-root, "."]
      pass_filenames: false
