name: Build and Deploy to Docker Hub

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Read and Stash Image Tag
        id: tag
        shell: bash
        run: |
          # Determine DOCKER_IMAGE_TAG based on conditions
          source .env
          if [[ -n "$ALTERNATE_REPO_NAME" ]] || [[ -n "$PORT" ]]; then
              chmod +x ${GITHUB_WORKSPACE}/scripts/environment/format.bash
              source ${GITHUB_WORKSPACE}/scripts/environment/format.bash
              chmod -x ${GITHUB_WORKSPACE}/scripts/environment/format.bash
          fi
          TAG=$DOCKER_IMAGE_TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: ${GITHUB_WORKSPACE}/image
          push: true
          tags: ${{ steps.tag.outputs.tag }}

