name: Run Bats Tests

on:
  pull_request:
    branches: security-review

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v7

      - name: Set up Docker
        uses: docker/setup-docker-action@v5

      - name: Install Bats
        shell: bash
        run: |
          chmod +x ${GITHUB_WORKSPACE}/scripts/setup/init.bash
          ${GITHUB_WORKSPACE}/scripts/setup/init.bash
          chmod -x ${GITHUB_WORKSPACE}/scripts/setup/init.bash
          
      - name: Run Bats tests
        id: test-run
        shell: bash
        run: |
          chmod +x ${GITHUB_WORKSPACE}/main.bash
          ${GITHUB_WORKSPACE}/main.bash
          chmod -x ${GITHUB_WORKSPACE}/main.bash
          
      - name: Fail if tests failed
        if: failure()
        run: exit 1
